db_host: &db_host "{{ env_var('DBT_HOST') }}"
db_username: &db_username "{{ env_var('DBT_USERNAME') }}"
db_password: &db_password "{{ env_var('DBT_PASSWORD') }}"
db_port: &db_port 5432
db_name: &db_name "{{ env_var('DBT_DB_NAME') }}"
threads: &threads 5

config:
  partial_parse: false
  fail_fast: true

reports_data:
  target: dev
  outputs:
    dev:
      type: postgres
      host: *db_host
      user: *db_username
      password: *db_password
      port: *db_port
      dbname: *db_name
      threads: *threads
      schema: "dev_{{ env_var('DBT_USERNAME') }}"
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections
      sslmode: prefer
    prod:
      type: postgres
      host: *db_host
      user: *db_username
      password: *db_password
      port: *db_port
      dbname: *db_name
      threads: *threads
      schema: public
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections
      sslmode: prefer