version: 2

models:
    - name: report_classifications
      description: "Report classifications"
      # columns:
      # - name: annotation_type
      #   description: "Type of the annotation"

sources:
  - name: label_studio
    schema: public
    tables:
      - name: task
      - name: task_completion
      # - name: project
  - name: raw_data
    schema: raw_data
    tables:
      - name: reports
